ignorePatterns:
  - "**/lib/*"
  - "**/node_modules/*"
env:
  node: true
  browser: true
  es6: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "prettier"
settings:
  react:
    version: detect
plugins:
  - "prettier"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - never
  prettier/prettier:
    - error
    - trailingComma: "all"
      singleQuote: true
      printWidth: 100
      endOfLine: "auto"
      semi: false
  react/prop-types:
    - 0
