env:
  node: true
  browser: true
  es6: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
